[window]
opacity = 0.9
padding.x = 0
padding.y = 0
dynamic_title = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "SemiBold"
bold.family = "FiraCode Nerd Font"
bold.style = "Bold"
italic.family = "FiraCode Nerd Font"
italic.style = "SemiBold"
bold_italic.family = "FiraCode Nerd Font"
bold_italic.style = "Bold"

size = 11.5

[general]
import = [
  "catppuccin-mocha.toml"
]
